# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec325a7b08c1b3e40f5626af7c67f415ea18f82f89620a183eb5c4c232ef6bb29c1057284d0647c6e55080ea18fad0c142fb5e9c960dab784cf84c2990d5b66d

test:
  secret_key_base: 2c75c89f9a148c7b975adfea550b08185e4bd6eb57abf3ae28584b852906500662df2503fe59b7020974c537489744fdc55d26c115e89ca1f97532ee5298a863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
